### ISSUE TITLE
[Bug] plot

### ISSUE THREAD

**Issue by SebGue** [Eomys/SciDataTool#25]
Hello,

If I try to plot data of an DataND object, I get the following error:
```
Data.plot_3D_Data("Speed", "Torque")
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "...\DataND\plot_3D_Data.py", line 188, in plot_3D_Data
    unit = unit_dict[axis.name]
KeyError: 'Speed'
```
I think the problem is, that I don't know how to 'tell' plot_3D_Data that the axis should be as is (and not SI).

Best regards, Sebastian

**Comment by SebGue** [comment]
... found a workaround.
`Data.plot_3D_Data("Speed{rpm}", "Torque{p.u.}")`
